import type {
  DashboardDefinition,
  DashboardRefreshEvent,
  DashboardSummary,
} from '../api/client'

export const dashboardID = 'dashboard-hydration-e2e'
export const draftDashboardID = 'dashboard-draft-e2e'

export const summary: DashboardSummary = {
  id: dashboardID,
  name: 'Hydration Smoke',
  description: 'Browser harness for dashboard hydration states.',
  status: 'live',
  widgetCount: 19,
  sourceCount: 5,
  createdAt: '2026-04-16T10:00:00Z',
  updatedAt: '2026-04-16T10:00:00Z',
  committedAt: '2026-04-16T10:00:00Z',
}

export const draftSummary: DashboardSummary = {
  id: draftDashboardID,
  name: 'Draft Customizer Smoke',
  description: 'Browser harness for draft widget editing.',
  status: 'draft',
  widgetCount: 2,
  sourceCount: 1,
  createdAt: '2026-04-16T10:00:00Z',
  updatedAt: '2026-04-16T10:00:00Z',
}

export const definition: DashboardDefinition = {
  schemaVersion: 2,
  id: dashboardID,
  name: 'Hydration Smoke',
  description: 'Browser harness for dashboard hydration states.',
  status: 'live',
  layout: { columns: 12 },
  createdAt: '2026-04-16T10:00:00Z',
  updatedAt: '2026-04-16T10:00:00Z',
  committedAt: '2026-04-16T10:00:00Z',
  sources: [
    { name: 'status', kind: 'runtime', config: {}, refresh: { mode: 'manual' } },
    { name: 'memories', kind: 'runtime', config: {}, refresh: { mode: 'manual' } },
    { name: 'usage', kind: 'runtime', config: {}, refresh: { mode: 'manual' } },
    { name: 'notes', kind: 'skill', config: {}, refresh: { mode: 'manual' } },
    { name: 'aiNews', kind: 'runtime', config: {}, refresh: { mode: 'manual' } },
  ],
  widgets: [
    {
      id: 'metric-widget',
      title: 'Active conversations',
      size: 'quarter',
      bindings: [{ source: 'status' }],
      code: { mode: 'preset', preset: 'metric', options: { path: 'activeConversationCount', format: 'integer', thresholds: [{ value: 4, tone: 'warn' }, { value: 6, tone: 'err' }] } },
      gridX: 0,
      gridY: 0,
      gridW: 3,
      gridH: 2,
    },
    {
      id: 'table-widget',
      title: 'Memory rows',
      size: 'half',
      bindings: [{ source: 'memories' }],
      code: { mode: 'preset', preset: 'table', options: { path: 'rows', columns: ['date', 'title', 'value'], limit: 4, pageSize: 2 } },
      gridX: 3,
      gridY: 0,
      gridW: 6,
      gridH: 3,
    },
    {
      id: 'list-widget',
      title: 'Agents',
      size: 'third',
      bindings: [{ source: 'status' }],
      code: { mode: 'preset', preset: 'list', options: { itemsPath: 'items', labelKey: 'title', subKey: 'state', visibleCount: 2 } },
      gridX: 9,
      gridY: 0,
      gridW: 3,
      gridH: 3,
    },
    {
      id: 'line-widget',
      title: 'Memories recorded',
      size: 'half',
      bindings: [{ source: 'memories' }],
      code: { mode: 'preset', preset: 'line_chart', options: { seriesPath: 'rows', x: 'date', y: 'value' } },
      gridX: 0,
      gridY: 3,
      gridW: 6,
      gridH: 3,
    },
    {
      id: 'bar-widget',
      title: 'Token usage per day',
      size: 'half',
      bindings: [{ source: 'usage' }],
      code: { mode: 'preset', preset: 'bar_chart', options: { seriesPath: 'series', x: 'date', y: 'value', color: '#6366f1' } },
      gridX: 6,
      gridY: 3,
      gridW: 6,
      gridH: 3,
    },
    {
      id: 'markdown-widget',
      title: 'Operations note',
      size: 'half',
      bindings: [{ source: 'notes' }],
      code: { mode: 'preset', preset: 'markdown', options: { path: 'text' } },
      gridX: 0,
      gridY: 6,
      gridW: 6,
      gridH: 2,
    },
    {
      id: 'news-widget',
      title: 'AI News',
      size: 'half',
      bindings: [{ source: 'aiNews' }],
      code: { mode: 'preset', preset: 'markdown', options: { path: 'headline', errorText: 'News source unavailable' } },
      gridX: 6,
      gridY: 6,
      gridW: 6,
      gridH: 2,
    },
    {
      id: 'code-widget',
      title: 'Code widget',
      size: 'quarter',
      bindings: [{ source: 'status' }],
      code: {
        mode: 'code',
        hash: 'phase-3b-fixture',
        tsx: 'import { Button, Details, TimeRangePicker } from "@atlas/ui"; export default function Widget(){ return null }',
        compiled: `import { h } from 'preact'
import { Card, Button, Details, TimeRangePicker, Text } from '@atlas/ui'

export default function Widget({ data }) {
  return h(Card, { title: 'Code actions', subtitle: 'Phase 3B bridge' }, [
    h('div', { style: 'display:flex;flex-direction:column;gap:8px', key: 'stack' }, [
      h(Button, { key: 'refresh', tone: 'accent', action: { action: 'refresh-source', source: 'status' } }, 'Refresh status'),
      h(Button, { key: 'filter', action: { action: 'set-filter', filterKey: 'source', value: 'status', title: 'status' } }, 'Filter status widgets'),
      h(Button, { key: 'nav', action: { action: 'navigate-dashboard', dashboardId: 'dashboard-draft-e2e' } }, 'Open draft'),
      h(TimeRangePicker, { key: 'range', value: '7d' }),
      h(Details, { key: 'details', summary: 'Open raw payload', title: 'Code widget payload', source: 'status', data }, h(Text, null, 'Inspect data')),
    ]),
  ])
}`,
      },
      gridX: 0,
      gridY: 8,
      gridW: 3,
      gridH: 2,
    },
    {
      id: 'progress-widget',
      title: 'System load',
      size: 'quarter',
      bindings: [{ source: 'status' }],
      code: { mode: 'preset', preset: 'progress', options: { path: 'activeConversationCount', max: 10, label: 'Active capacity', format: 'integer', unitLabel: 'chats', thresholds: [{ value: 4, tone: 'warn', label: 'Busy' }, { value: 6, tone: 'err', label: 'Overloaded' }] } },
      gridX: 3,
      gridY: 8,
      gridW: 3,
      gridH: 2,
    },
    {
      id: 'gauge-widget',
      title: 'Usage gauge',
      size: 'quarter',
      bindings: [{ source: 'status' }],
      code: { mode: 'preset', preset: 'gauge', options: { path: 'activeConversationCount', max: 10, label: 'Active chats', format: 'integer', unitLabel: 'chats', thresholds: [{ value: 4, tone: 'warn' }, { value: 6, tone: 'err' }] } },
      gridX: 6,
      gridY: 8,
      gridW: 3,
      gridH: 2,
    },
    {
      id: 'status-grid-widget',
      title: 'Agent status',
      size: 'quarter',
      bindings: [{ source: 'status' }],
      code: { mode: 'preset', preset: 'status_grid', options: { itemsPath: 'items', labelKey: 'title', statusKey: 'state', limit: 4, valueMap: { reviewing: 'Needs review' } } },
      gridX: 9,
      gridY: 8,
      gridW: 3,
      gridH: 2,
    },
    {
      id: 'area-chart-widget',
      title: 'Usage trend',
      size: 'half',
      bindings: [{ source: 'usage' }],
      code: { mode: 'preset', preset: 'area_chart', options: { seriesPath: 'series', x: 'date', y: 'value', format: 'compact', palette: 'ocean' } },
      gridX: 0,
      gridY: 10,
      gridW: 6,
      gridH: 3,
    },
    {
      id: 'pie-chart-widget',
      title: 'Usage mix',
      size: 'third',
      bindings: [{ source: 'usage' }],
      code: { mode: 'preset', preset: 'pie_chart', options: { seriesPath: 'segments', labelKey: 'label', valueKey: 'value', format: 'compact', palette: 'warm' } },
      gridX: 6,
      gridY: 10,
      gridW: 4,
      gridH: 3,
    },
    {
      id: 'kpi-group-widget',
      title: 'Team KPIs',
      size: 'third',
      bindings: [{ source: 'status' }],
      code: { mode: 'preset', preset: 'kpi_group', options: { itemsPath: 'metrics', labelKey: 'label', valueKey: 'value', deltaKey: 'delta', format: 'integer' } },
      gridX: 10,
      gridY: 10,
      gridW: 2,
      gridH: 3,
    },
    {
      id: 'donut-chart-widget',
      title: 'Usage donut',
      size: 'third',
      bindings: [{ source: 'usage' }],
      code: { mode: 'preset', preset: 'donut_chart', options: { seriesPath: 'segments', labelKey: 'label', valueKey: 'value', format: 'compact', palette: 'forest' } },
      gridX: 0,
      gridY: 13,
      gridW: 4,
      gridH: 3,
    },
    {
      id: 'scatter-chart-widget',
      title: 'Latency spread',
      size: 'half',
      bindings: [{ source: 'status' }],
      code: { mode: 'preset', preset: 'scatter_chart', options: { seriesPath: 'scatter', x: 'x', y: 'y', format: 'integer', unitLabel: 'ms', palette: 'ocean' } },
      gridX: 4,
      gridY: 13,
      gridW: 6,
      gridH: 3,
    },
    {
      id: 'stacked-chart-widget',
      title: 'Queue balance',
      size: 'third',
      bindings: [{ source: 'status' }],
      code: { mode: 'preset', preset: 'stacked_chart', options: { seriesPath: 'stacked', x: 'date', seriesKeys: ['open', 'closed'], format: 'integer', palette: 'slate' } },
      gridX: 10,
      gridY: 13,
      gridW: 2,
      gridH: 3,
    },
    {
      id: 'timeline-widget',
      title: 'Ops timeline',
      size: 'half',
      bindings: [{ source: 'status' }],
      code: { mode: 'preset', preset: 'timeline', options: { itemsPath: 'events', timeKey: 'date', labelKey: 'title', bodyKey: 'summary', statusKey: 'state', valueMap: { warn: 'Attention' } } },
      gridX: 0,
      gridY: 16,
      gridW: 6,
      gridH: 3,
    },
    {
      id: 'heatmap-widget',
      title: 'Daily intensity',
      size: 'half',
      bindings: [{ source: 'status' }],
      code: { mode: 'preset', preset: 'heatmap', options: { seriesPath: 'daily', dateKey: 'date', valueKey: 'value', format: 'integer', palette: 'warm' } },
      gridX: 6,
      gridY: 16,
      gridW: 6,
      gridH: 3,
    },
  ],
}

export const draftDefinition: DashboardDefinition = {
  schemaVersion: 2,
  id: draftDashboardID,
  name: 'Draft Customizer Smoke',
  description: 'Browser harness for draft widget editing.',
  status: 'draft',
  layout: { columns: 12 },
  createdAt: '2026-04-16T10:00:00Z',
  updatedAt: '2026-04-16T10:00:00Z',
  sources: [
    { name: 'status', kind: 'runtime', config: {}, refresh: { mode: 'manual' } },
  ],
  widgets: [
    {
      id: 'draft-metric-widget',
      title: 'Draft metric',
      description: 'Editable widget',
      size: 'quarter',
      bindings: [{ source: 'status' }],
      code: { mode: 'preset', preset: 'metric', options: { path: 'activeConversationCount', format: 'integer' } },
      gridX: 0,
      gridY: 0,
      gridW: 3,
      gridH: 1,
    },
    {
      id: 'draft-code-widget',
      title: 'Draft code',
      description: 'Editable code widget',
      size: 'half',
      bindings: [{ source: 'status' }],
      code: {
        mode: 'code',
        hash: 'draft-code-initial',
        tsx: `import { Card, Text } from '@atlas/ui'

export default function Widget() {
  return (
    <Card title="Draft code widget">
      <Text>Initial code widget</Text>
    </Card>
  )
}
`,
        compiled: `import { h } from 'preact'
import { Card, Text } from '@atlas/ui'
export default function Widget() {
  return h(Card, { title: 'Draft code widget' }, h(Text, null, 'Initial code widget'))
}`,
      },
      gridX: 3,
      gridY: 0,
      gridW: 6,
      gridH: 2,
    },
  ],
}

export const initialEvents: DashboardRefreshEvent[] = [
  {
    dashboardId: dashboardID,
    source: 'status',
    sourceKind: 'runtime',
    success: true,
    data: {
      activeConversationCount: 3,
      latencyMs: 182,
      metrics: [
        { label: 'Open tasks', value: 18, delta: 2.4, tone: 'ok' },
        { label: 'Alerts', value: 3, delta: -1.2, tone: 'warn' },
        { label: 'Blocked', value: 1, delta: 0, tone: 'neutral' },
      ],
      scatter: [
        { x: 1, y: 120 },
        { x: 2, y: 210 },
        { x: 3, y: 182 },
      ],
      stacked: [
        { date: 'Mon', open: 7, closed: 4 },
        { date: 'Tue', open: 5, closed: 6 },
        { date: 'Wed', open: 8, closed: 3 },
      ],
      events: [
        { date: '2026-04-16T08:45:00Z', title: 'Atlas started', summary: 'Runtime boot completed', state: 'ok' },
        { date: '2026-04-16T09:15:00Z', title: 'Refresh lag', summary: 'One source retried', state: 'warn' },
      ],
      daily: [
        { date: '2026-04-08', value: 2 },
        { date: '2026-04-09', value: 4 },
        { date: '2026-04-10', value: 6 },
      ],
      items: [
        { title: 'agent-alpha', state: 'idle' },
        { title: 'agent-beta', state: 'thinking' },
        { title: 'agent-gamma', state: 'running' },
      ],
    },
    at: '2026-04-16T10:00:01Z',
    resolvedAt: '2026-04-16T10:00:01Z',
    durationMs: 12,
    lastSuccessfulAt: '2026-04-16T10:00:01Z',
  },
  {
    dashboardId: dashboardID,
    source: 'memories',
    sourceKind: 'runtime',
    success: true,
    data: {
      rows: [
        { date: '2026-04-10', title: 'preferences', value: 4 },
        { date: '2026-04-11', title: 'projects', value: 6 },
        { date: '2026-04-12', title: 'workflow', value: 9 },
      ],
    },
    at: '2026-04-16T10:00:02Z',
    resolvedAt: '2026-04-16T10:00:02Z',
    durationMs: 14,
    lastSuccessfulAt: '2026-04-16T10:00:02Z',
  },
  {
    dashboardId: dashboardID,
    source: 'usage',
    sourceKind: 'runtime',
    success: true,
    data: {
      series: [
        { date: 'Mon', value: 1200 },
        { date: 'Tue', value: 1800 },
        { date: 'Wed', value: 2400 },
      ],
      segments: [
        { label: 'Chat', value: 4200 },
        { label: 'Workflows', value: 900 },
        { label: 'Research', value: 300 },
      ],
    },
    at: '2026-04-16T10:00:03Z',
    resolvedAt: '2026-04-16T10:00:03Z',
    durationMs: 16,
    lastSuccessfulAt: '2026-04-16T10:00:03Z',
  },
  {
    dashboardId: dashboardID,
    source: 'notes',
    sourceKind: 'skill',
    success: true,
    data: { text: '### Operations note\nAll dashboard presets hydrated from source events.' },
    at: '2026-04-16T10:00:04Z',
    resolvedAt: '2026-04-16T10:00:04Z',
    durationMs: 18,
    lastSuccessfulAt: '2026-04-16T10:00:04Z',
  },
  {
    dashboardId: dashboardID,
    source: 'aiNews',
    sourceKind: 'runtime',
    success: false,
    error: 'runtime endpoint /usage/summary returned 401',
    at: '2026-04-16T10:00:05Z',
    resolvedAt: '2026-04-16T10:00:05Z',
    durationMs: 20,
  },
]

export const refreshedEvents: DashboardRefreshEvent[] = [
  {
    dashboardId: dashboardID,
    source: 'status',
    sourceKind: 'runtime',
    success: true,
    data: {
      activeConversationCount: 4,
      latencyMs: 204,
      metrics: [
        { label: 'Open tasks', value: 21, delta: 3.1, tone: 'ok' },
        { label: 'Alerts', value: 2, delta: -1.6, tone: 'ok' },
        { label: 'Blocked', value: 1, delta: 0, tone: 'neutral' },
      ],
      scatter: [
        { x: 1, y: 120 },
        { x: 2, y: 210 },
        { x: 3, y: 204 },
        { x: 4, y: 168 },
      ],
      stacked: [
        { date: 'Mon', open: 7, closed: 4 },
        { date: 'Tue', open: 5, closed: 6 },
        { date: 'Wed', open: 8, closed: 3 },
        { date: 'Thu', open: 6, closed: 5 },
      ],
      events: [
        { date: '2026-04-16T08:45:00Z', title: 'Atlas started', summary: 'Runtime boot completed', state: 'ok' },
        { date: '2026-04-16T09:15:00Z', title: 'Refresh lag', summary: 'One source retried', state: 'warn' },
        { date: '2026-04-16T10:05:00Z', title: 'Queue settled', summary: 'Background tasks drained', state: 'ok' },
      ],
      daily: [
        { date: '2026-04-08', value: 2 },
        { date: '2026-04-09', value: 4 },
        { date: '2026-04-10', value: 6 },
        { date: '2026-04-11', value: 5 },
      ],
      items: [
        { title: 'agent-alpha', state: 'idle' },
        { title: 'agent-beta', state: 'thinking' },
        { title: 'agent-delta', state: 'running' },
        { title: 'agent-epsilon', state: 'reviewing' },
      ],
    },
    at: '2026-04-16T10:01:01Z',
    resolvedAt: '2026-04-16T10:01:01Z',
    durationMs: 11,
    lastSuccessfulAt: '2026-04-16T10:01:01Z',
  },
  {
    dashboardId: dashboardID,
    source: 'memories',
    sourceKind: 'runtime',
    success: true,
    data: {
      rows: [
        { date: '2026-04-10', title: 'preferences', value: 4 },
        { date: '2026-04-11', title: 'projects', value: 6 },
        { date: '2026-04-12', title: 'workflow', value: 9 },
        { date: '2026-04-13', title: 'facts', value: 12 },
      ],
    },
    at: '2026-04-16T10:01:02Z',
    resolvedAt: '2026-04-16T10:01:02Z',
    durationMs: 13,
    lastSuccessfulAt: '2026-04-16T10:01:02Z',
  },
  {
    dashboardId: dashboardID,
    source: 'usage',
    sourceKind: 'runtime',
    success: true,
    data: {
      series: [
        { date: 'Mon', value: 1200 },
        { date: 'Tue', value: 1800 },
        { date: 'Wed', value: 2400 },
        { date: 'Thu', value: 1550 },
      ],
      segments: [
        { label: 'Chat', value: 4700 },
        { label: 'Workflows', value: 950 },
        { label: 'Research', value: 350 },
      ],
    },
    at: '2026-04-16T10:01:03Z',
    resolvedAt: '2026-04-16T10:01:03Z',
    durationMs: 15,
    lastSuccessfulAt: '2026-04-16T10:01:03Z',
  },
  {
    dashboardId: dashboardID,
    source: 'notes',
    sourceKind: 'skill',
    success: false,
    error: 'notes skill timed out',
    at: '2026-04-16T10:01:04Z',
    resolvedAt: '2026-04-16T10:01:04Z',
    durationMs: 5000,
    lastSuccessfulAt: '2026-04-16T10:00:04Z',
    stale: true,
  },
  {
    dashboardId: dashboardID,
    source: 'aiNews',
    sourceKind: 'runtime',
    success: false,
    error: 'runtime endpoint /usage/summary returned 401',
    at: '2026-04-16T10:01:05Z',
    resolvedAt: '2026-04-16T10:01:05Z',
    durationMs: 19,
  },
]
